pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    stage('Removing the old Image'){
      steps{
        sh '''docker image rmi node:16-alpine'''
      }
    }
  }
}
