pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    stages{
      stage('Waiting for 5 seconds'){
        steps{
          sh 'sleep 5'
        }
      }
    }
    stage('Removing Unused Images'){
      steps {
        sh 'docker image prune -af'
      }
    }
  }
}
