pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    stage('Waiting for 5 seconds'){
      steps{
        sh 'sleep 5'
      }
    }
  }
}
